### ISSUE TITLE
Support for tags

### ISSUE THREAD

**Issue by pomek** [cksource/mrgit#148]
### 🎯 Goals

- The goal is to allow checking out a repository to a tag (version) instead of a branch.
- The tag can be unknown, so we want to check out the latest created.

### 📗 Story

- **Given**: I am a developer who uses the https://github.com/ckeditor/ckeditor5-dev repository in a project.
	```json
	{
	  "packages": "external/",
	  "dependencies": {
	    "ckeditor5-dev": "ckeditor/ckeditor5-dev@latest"
	  }
	}
	```
- **When**: I execute `mrgit sync`.
- **Then**: The tool checks out the `ckeditor5-dev` repository on the `v31.1.11` tag.

### 💡 Hints

- When creating the issue, the latest version in `ckeditor5-dev` is `v31.1.11`
	<img width="234" alt="image" src="https://user-images.githubusercontent.com/2270764/203640747-ee76f9b9-6227-4e8d-a180-f7bf24554b5f.png">
- We should also support defining a particular tag: `"ckeditor5-dev": "ckeditor/ckeditor5-dev@v31.0.0"`.
- The `@latest` has a specific meaning - find the latest tag name and use it.

**Comment by przemyslaw-zan** [comment]
[Branch](https://github.com/cksource/mrgit/compare/i/148).

Support for using tags while cloning the repository is almost complete. For whatever reason, calling:

```bash
LATEST=$( git describe --abbrev=0 --tags ) && git checkout --quiet $LATEST
```

Works fine locally, but when trying to do it via script, it throws an error:

```
'LATEST' is not recognized as an internal or external command, operable program or batch file.
```

After I fix this, I will also have to implement this functionality for updating the repository, not just updating it.

Question: Is it okay for the checked out tag to be in a detached head state?

**Comment by przemyslaw-zan** [comment]
Separate syntax for tags and branches could be benefitial for clarity while defining configuration in the `mrgit.json` file.

- branches - `#`: `organization/repository#release`
- tags - `@`: `organization/repository@latest`

However, while I can ensure that anything following `@` is a tag by using the `tags/` prefix while checking out, there is no way that I found to ensure that `#` is always followed by a branch. This means, that `#v30.0.0` is technically a valid syntax, even though it should not be.

**Comment by pomek** [comment]
That makes sense. We could detect if a tag is specified with the branch symbol, but I guess it is not worth it. So, when passing both: `#v35.0.0` and `@35.0.0` as a suffix, the application should accept them. When passing `@latest`, it tries to check out the latest tag. But passing `#latest` is about checking out a branch.

**Comment by przemyslaw-zan** [comment]
Should we assume that tags should always contain semantic version number with possibility of additional characters, (eg. `@v35.0.0`) or should we allow any tag name? (eg. `@tagname`)?

`@latest` is a separate case, so I'm assking about other cases.
